In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

The first step is to import all the necessary libraries by using their aliases so we can use them without a hassle.

# Getting Started with Data Analysis using Pandas

In [340]:
df = pd.read_csv('survey_results_public.csv')

df.head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            EduOther  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    OrgSize  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             DevType YearsCode Age1stCode  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       YearsCodePro           CareerSat                 JobSat  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               MgrIdiot  MgrMoney   MgrWant  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             JobSeek          LastHireDate  \
0                                                NaN                   NaN

By using the read_csv() method, we read the dataset and viewed the top 5 entries by using head() function.

The data we will use in this notebook is called "StackOverflow Annual Developer Survey" data of 2019.

It contains two datasets namely "Public" and "Schema". The Public dataset is the survey data while the Schema dataset explains each column of the Public data and their meaning.

In [14]:
df.shape

(88883, 85)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Respondent              88883 non-null  int64  
 1   MainBranch              88331 non-null  object 
 2   Hobbyist                88883 non-null  object 
 3   OpenSourcer             88883 non-null  object 
 4   OpenSource              86842 non-null  object 
 5   Employment              87181 non-null  object 
 6   Country                 88751 non-null  object 
 7   Student                 87014 non-null  object 
 8   EdLevel                 86390 non-null  object 
 9   UndergradMajor          75614 non-null  object 
 10  EduOther                84260 non-null  object 
 11  OrgSize                 71791 non-null  object 
 12  DevType                 81335 non-null  object 
 13  YearsCode               87938 non-null  object 
 14  Age1stCode              87634 non-null

Here we used the shape attribute to return the total number of rows and columns of the dataset. And the info() function is a convenient method to see the jist of the entire dataset.

It shows the number of columns with their names and data types and number of entries in them. This is a way to confirm if we can have some null values in the Dataset.

For example, in this we can see that, while  the total entries are 88883, second column has 88331 entires which means it has null values

In [112]:
schema_df = pd.read_csv('survey_results_schema.csv',index_col = 'Column')

schema_df

QuestionText
Column                                                                   
Respondent              Randomized respondent ID number (not in order ...
MainBranch              Which of the following options best describes ...
Hobbyist                                          Do you code as a hobby?
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
Employment              Which of the following best describes your cur...
Country                         In which country do you currently reside?
Student                 Are you currently enrolled in a formal, degree...
EdLevel                 Which of the following best describes the high...
UndergradMajor          What was your main or most important field of ...
EduOther                Which of the following types of non-degree edu...
OrgSize                 Approximately how many people are employed by ...
DevType                 Which of the following describe you? Please se...
YearsCode               Including any education, how many years have y...
Age1stCode              At what age did you write your first line of c...
YearsCodePro            How many years have you coded professionally (...
CareerSat               Overall, how satisfied are you with your caree...
JobSat                  How satisfied are you with your current job? (...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
JobSeek                 Which of the following best describes your cur...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
JobFactors              Imagine that you are deciding between two job ...
ResumeUpdate            Think back to the last time you updated your r...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
ConvertedComp           Salary converted to annual USD salaries using ...
WorkWeekHrs              On average, how many hours per week do you work?
WorkPlan                          How structured or planned is your work?
WorkChallenge           Of these options, what are your greatest chall...
WorkRemote                                How often do you work remotely?
WorkLoc                                   Where would you prefer to work?
ImpSyn                  For the specific work you do, and the years of...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
UnitTests               Does your company regularly employ unit tests ...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, 

Here, we loaded the "Schema" dataset which displays the meaning of all the columns. 

Notice that we cannot see all the rows in this dataset as Pandas minimises these for not taking up too much of screen space. 

But in cases like these where its essential to see all the rows, we can use a method called set_option() as shown below

In [12]:
pd.set_option('display.max_rows',85)

By setting the maximum rows to be displayed as 85, we can clearly see all the rows of the "Schema" dataset now

In [15]:
schema_df

Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the f

Right now, this might not be an efficient method to constantly come back to this Dataframe to see the meaning of the columns in "Public" but as we move down further, we will discuss about various filtering and accessing methods which will make our job easier.

For example, the row named "Country" in the "Schema" dataframe asks a question stating "In which country do you currently reside?", while the rows in the "Public" dataframe contains a list of country names in which various people who were surveyed reside in.

Note:

1. Dataframe is a 2 Dimensional Structure as it has rows and columns and it is a concatenation of multiple series.
2. Series is a 1 Dimensional Structure and it is a lot similar to 1D arrays with more functionalities

In [16]:
df['Country']

0                United Kingdom
1        Bosnia and Herzegovina
2                      Thailand
3                 United States
4                       Ukraine
                  ...          
88878                    Canada
88879                       NaN
88880                       NaN
88881                       NaN
88882                     Spain
Name: Country, Length: 88883, dtype: object

We can access a single column in the dataframe by specifying it within the paranthesis of the dataframe as shown above.

For multiple columns, we use a list of columns inside the paranthesis.

In [17]:
df[['Country','Hobbyist']]

Country Hobbyist
0              United Kingdom      Yes
1      Bosnia and Herzegovina       No
2                    Thailand      Yes
3               United States       No
4                     Ukraine      Yes
...                       ...      ...
88878                  Canada      Yes
88879                     NaN       No
88880                     NaN       No
88881                     NaN       No
88882                   Spain      Yes

[88883 rows x 2 columns]

We can see that, when we used a single column, we can see that a Series is returned while when passing multiple columns, we can see that a DataFrame is returned

In [18]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

# iloc and loc 

There is a lot of confusion regarding the usage of the functions "iloc" and "loc" so let's talk about this in a detailed manner by using lots of examples of iloc and loc

First, let us proceed with iloc

"iloc" stands for "Integer Location" and this is used to identify or locate the values present in the Dataframe by using the integers as its indexes.

There are several ways of accessing the data by using iloc so let us list them.

1. By specifying only the row
2. By specifying multiple rows
3. By specifying a row and a specific column
4. By specifying single/multiple row/rows and single/multiple column/columns

Now, let us look at how we can access all the data present in a single row by using "iloc". By default, the parameter list of iloc is [rows,columns] so rows come first followed by columns.

But since in this case, we need everything from columns, we dont specify an index for the column.

Below is the example

In [59]:
df.iloc[0] #First row is specified and we get all the data for the 1st row

Respondent                                                                1
MainBranch                           I am a student who is learning to code
Hobbyist                                                                Yes
OpenSourcer                                                           Never
OpenSource                The quality of OSS and closed source software ...
Employment                           Not employed, and not looking for work
Country                                                      United Kingdom
Student                                                                  No
EdLevel                                           Primary/elementary school
UndergradMajor                                                          NaN
EduOther                  Taught yourself a new language, framework, or ...
OrgSize                                                                 NaN
DevType                                                                 NaN
YearsCode   

Now, let us look at how we can access the data of multiple rows by using iloc.

So for accessing multiple rows, there are two ways in which we can do them.

1. By specifying the indexes of the rows as a list
2. By slicing the indexes just like we do in lists


1. In the first method, we pass the indexes of the rows we want to access,as a list inside the iloc function. The syntax for this is df.iloc[[row1,row2,...,rown]]. 

While using only 2 columns, we have to be vary of specifying them as a list as df.iloc[[x,y]] is entierly different from df.iloc[x,y] as in second case, it returns a single value at xth row and yth column and not a dataframe of x and y rows as we need

2. In the second method, we pass the indexes as a slicing operation between a range so the dataframe is returned for that particular range. Keep note that, the range in iloc is exclusive of outer bound which means, the values are returned one less than outer bound.

Now, let us look at the examples

In [62]:
#Accessing multiple rows by passing row indexes as a list
df.iloc[[0,3]]

Respondent                              MainBranch Hobbyist OpenSourcer  \
0           1  I am a student who is learning to code      Yes       Never   
3           4          I am a developer by profession       No       Never   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   

                               Employment         Country Student  \
0  Not employed, and not looking for work  United Kingdom      No   
3                      Employed full-time   United States      No   

                                    EdLevel  \
0                 Primary/elementary school   
3  Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
3  Computer science, computer engineering, or sof...   

                                            EduOther               OrgSize  \
0  Taught yourself a new language, framework, or ...                   NaN   
3  Taken an online course in programming or softw...  100 to 499 employees   

                 DevType YearsCode Age1stCode      YearsCodePro  \
0                    NaN         4         10               NaN   
3  Developer, full-stack         3         16  Less than 1 year   

        CareerSat              JobSat        MgrIdiot MgrMoney   MgrWant  \
0             NaN                 NaN             NaN      NaN       NaN   
3  Very satisfied  Slightly satisfied  Very confident       No  Not sure   

                                        JobSeek          LastHireDate  \
0                                           NaN                   NaN   
3  I am not interested in new job opportunities  Less than a year ago   

                                             LastInt FizzBuzz  \
0                                                NaN      NaN   
3  Write code by hand (e.g., on a whiteboard);Int...       No   

                                          JobFactors  \
0                                                NaN   
3  Languages, frameworks, and other technologies ...   

                       ResumeUpdate CurrencySymbol          CurrencyDesc  \
0                               NaN            NaN                   NaN   
3  I was preparing for a job search            USD  United States dollar   

   CompTotal CompFreq  ConvertedComp  WorkWeekHrs  \
0        NaN      NaN            NaN          NaN   
3    61000.0   Yearly        61000.0         80.0   

                                            WorkPlan WorkChallenge  \
0                                                NaN           NaN   
3  There's no schedule or spec; I work on what se...           NaN   

                         WorkRemote WorkLoc                  ImpSyn CodeRev  \
0                               NaN     NaN                     NaN     NaN   
3  Less than once per month / Never    Home  A little below average      No   

   CodeRevHrs                  UnitTests  \
0         NaN                        NaN   
3         NaN  No, but I think we should   

                                         PurchaseHow  \
0                                                NaN   
3  Developers typically have the most influence o...   

                    PurchaseWhat               LanguageWorkedWith  \
0                            NaN  HTML/CSS;Java;JavaScript;Python   
3  I have little or no influence              C;C++;C#;Python;SQL   

                            LanguageDesireNextYear DatabaseWorkedWith  \
0  C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL             SQLite   
3                              C;C#;JavaScript;SQL       MySQL;SQLite   

  DatabaseDesireNextYear PlatformWorkedWith   PlatformDesireNextYear  \
0                  MySQL      MacOS;Windows  Android;Arduino;Windows   
3           MySQL;SQLite      Linux;Windows            Linux;Windows   

  WebFrameWorkedWith WebFrameDesireNextYear 

In [66]:
df.iloc[1,3]

#Note here that df.iloc[[1,3]] != df.iloc[1,3] as 3 here means the column index and not row index

'Less than once per year'

In [67]:
df.iloc[2:4] #As iloc is exclusive of outer bound, only indexes 2 and 3 are returned in this case.



Respondent                                         MainBranch Hobbyist  \
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   

  OpenSourcer                                         OpenSource  \
2       Never  The quality of OSS and closed source software ...   
3       Never  The quality of OSS and closed source software ...   

           Employment        Country Student  \
2  Employed full-time       Thailand      No   
3  Employed full-time  United States      No   

                                    EdLevel  \
2  Bachelor’s degree (BA, BS, B.Eng., etc.)   
3  Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   

                                            EduOther               OrgSize  \
2  Taught yourself a new language, framework, or ...  100 to 499 employees   
3  Taken an online course in programming or softw...  100 to 499 employees   

                                             DevType YearsCode Age1stCode  \
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   

       YearsCodePro           CareerSat              JobSat  \
2                 1  Slightly satisfied  Slightly satisfied   
3  Less than 1 year      Very satisfied  Slightly satisfied   

               MgrIdiot  MgrMoney   MgrWant  \
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   

                                             JobSeek          LastHireDate  \
2  I’m not actively looking, but I am open to new...         1-2 years ago   
3       I am not interested in new job opportunities  Less than a year ago   

                                             LastInt FizzBuzz  \
2                Interview with people in peer roles       No   
3  Write code by hand (e.g., on a whiteboard);Int...       No   

                                          JobFactors  \
2  Languages, frameworks, and other technologies ...   
3  Languages, frameworks, and other technologies ...   

                       ResumeUpdate CurrencySymbol          CurrencyDesc  \
2  I was preparing for a job search            THB             Thai baht   
3  I was preparing for a job search            USD  United States dollar   

   CompTotal CompFreq  ConvertedComp  WorkWeekHrs  \
2    23000.0  Monthly         8820.0         40.0   
3    61000.0   Yearly        61000.0         80.0   

                                            WorkPlan  \
2  There's no schedule or spec; I work on what se...   
3  There's no schedule or spec; I work on what se...   

                                       WorkChallenge  \
2  Distracting work environment;Inadequate access...   
3                                                NaN   

                         WorkRemote WorkLoc                  ImpSyn CodeRev  \
2  Less than once per month / Never    Home                 Average      No   
3  Less than once per month / Never    Home  A little below average      No   

   CodeRevHrs                  UnitTests  \
2         NaN  No, but I think we should   
3         NaN  No, but I think we should   

                                         PurchaseHow  \
2                                           Not sure   
3  Developers typically have the most influence o...   

                    PurchaseWhat   LanguageWorkedWith LanguageDesireNextYear  \
2  I have little or no influence             HTML/CSS        Elixir;HTML/CSS   
3  I have little or no influence  C;C++;C#;Python;SQL    C;C#;JavaScript;SQL   

  DatabaseWorkedWith DatabaseDesireNextYear PlatformWorkedWith  \
2         PostgreSQL             PostgreSQL                NaN   
3       MySQL;SQLite           MySQL;SQLite      Linux;Windows   

  Pl

An important thing to notw while using slicing is that we should not pass them inside a list while using the iloc or loc function. The syntax shoule be like

df.iloc[rowx:rowy,colx:coly]

df.loc[rowx:rowy,"colnamex":"colnamey"]

Now, let us see how we can access a specific element by using iloc. The default syntax is df.iloc[row,column] so we use this to access one element.

Let us look at an example below

In [68]:
df.iloc[0,3] #This returns the value present in 1st row and 4th column

'Never'

Now, let us look at the way in which we can access the dataframe by specifying multiple rows and multiple columns. 

The way is simple as all we need to do is to pass the multiple rows and columns as a list and pass them inside the iloc function.

Let us look at the example below

In [69]:
df.iloc[[0,1],[3,4]] #This returns the dataframe having 2 rows which are 0,1 rows of orginal and 2 columns which are 3 and 4

OpenSourcer                                         OpenSource
0                    Never  The quality of OSS and closed source software ...
1  Less than once per year  The quality of OSS and closed source software ...

Now, that we have succesfully seen the iloc function, let us talk about the loc function.

"loc" stands for location and in this function, we can access certain elements or the dataframe by specifying the indexes of the row and the "name" of the column. 

If we try to access the dataframe or a value by specifying the column index, it throws an error.

The methods are similar to the "loc" just like iloc but the slicing operation's range is inclusive in this case. This means that the upper bound is considered too for the "loc" operation.

Now, let us look at the examples just like iloc

In [72]:
df.iloc[0] #First row is specified and we get all the data for the 1st row

Respondent                                                                1
MainBranch                           I am a student who is learning to code
Hobbyist                                                                Yes
OpenSourcer                                                           Never
OpenSource                The quality of OSS and closed source software ...
Employment                           Not employed, and not looking for work
Country                                                      United Kingdom
Student                                                                  No
EdLevel                                           Primary/elementary school
UndergradMajor                                                          NaN
EduOther                  Taught yourself a new language, framework, or ...
OrgSize                                                                 NaN
DevType                                                                 NaN
YearsCode   

In [73]:
#Accessing multiple rows by passing row indexes as a list
df.loc[[0,3]]


Respondent                              MainBranch Hobbyist OpenSourcer  \
0           1  I am a student who is learning to code      Yes       Never   
3           4          I am a developer by profession       No       Never   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   

                               Employment         Country Student  \
0  Not employed, and not looking for work  United Kingdom      No   
3                      Employed full-time   United States      No   

                                    EdLevel  \
0                 Primary/elementary school   
3  Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
3  Computer science, computer engineering, or sof...   

                                            EduOther               OrgSize  \
0  Taught yourself a new language, framework, or ...                   NaN   
3  Taken an online course in programming or softw...  100 to 499 employees   

                 DevType YearsCode Age1stCode      YearsCodePro  \
0                    NaN         4         10               NaN   
3  Developer, full-stack         3         16  Less than 1 year   

        CareerSat              JobSat        MgrIdiot MgrMoney   MgrWant  \
0             NaN                 NaN             NaN      NaN       NaN   
3  Very satisfied  Slightly satisfied  Very confident       No  Not sure   

                                        JobSeek          LastHireDate  \
0                                           NaN                   NaN   
3  I am not interested in new job opportunities  Less than a year ago   

                                             LastInt FizzBuzz  \
0                                                NaN      NaN   
3  Write code by hand (e.g., on a whiteboard);Int...       No   

                                          JobFactors  \
0                                                NaN   
3  Languages, frameworks, and other technologies ...   

                       ResumeUpdate CurrencySymbol          CurrencyDesc  \
0                               NaN            NaN                   NaN   
3  I was preparing for a job search            USD  United States dollar   

   CompTotal CompFreq  ConvertedComp  WorkWeekHrs  \
0        NaN      NaN            NaN          NaN   
3    61000.0   Yearly        61000.0         80.0   

                                            WorkPlan WorkChallenge  \
0                                                NaN           NaN   
3  There's no schedule or spec; I work on what se...           NaN   

                         WorkRemote WorkLoc                  ImpSyn CodeRev  \
0                               NaN     NaN                     NaN     NaN   
3  Less than once per month / Never    Home  A little below average      No   

   CodeRevHrs                  UnitTests  \
0         NaN                        NaN   
3         NaN  No, but I think we should   

                                         PurchaseHow  \
0                                                NaN   
3  Developers typically have the most influence o...   

                    PurchaseWhat               LanguageWorkedWith  \
0                            NaN  HTML/CSS;Java;JavaScript;Python   
3  I have little or no influence              C;C++;C#;Python;SQL   

                            LanguageDesireNextYear DatabaseWorkedWith  \
0  C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL             SQLite   
3                              C;C#;JavaScript;SQL       MySQL;SQLite   

  DatabaseDesireNextYear PlatformWorkedWith   PlatformDesireNextYear  \
0                  MySQL      MacOS;Windows  Android;Arduino;Windows   
3           MySQL;SQLite      Linux;Windows            Linux;Windows   

  WebFrameWorkedWith WebFrameDesireNextYear 

In [74]:
df.loc[1,3]

#This throws an error as loc doesnt accept column indexes

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [3] of <class 'int'>

In [75]:
df.loc[2:4] #As iloc is inclusive of outer bound unlike iloc, so indexes 2,3 and 4 are returned in this case

Respondent                                         MainBranch Hobbyist  \
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource          Employment  \
2  The quality of OSS and closed source software ...  Employed full-time   
3  The quality of OSS and closed source software ...  Employed full-time   
4  OSS is, on average, of HIGHER quality than pro...  Employed full-time   

         Country Student                                   EdLevel  \
2       Thailand      No  Bachelor’s degree (BA, BS, B.Eng., etc.)   
3  United States      No  Bachelor’s degree (BA, BS, B.Eng., etc.)   
4        Ukraine      No  Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            EduOther  \
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    OrgSize  \
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             DevType YearsCode Age1stCode  \
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       YearsCodePro           CareerSat                 JobSat  \
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               MgrIdiot  MgrMoney   MgrWant  \
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             JobSeek          LastHireDate  \
2  I’m not actively looking, but I am open to new...         1-2 years ago   
3       I am not interested in new job opportunities  Less than a year ago   
4       I am not interested in new job opportunities  Less than a year ago   

                                             LastInt FizzBuzz  \
2                Interview with people in peer roles       No   
3  Write code by hand (e.g., on a whiteboard);Int...       No   
4  Write any code;Write code by hand (e.g., on a ...       No   

                                          JobFactors  \
2  Languages, frameworks, and other technologies ...   
3  Languages, frameworks, and other technologies ...   
4  Industry that I'd be working in;Languages, fra...   

                       ResumeUpdate CurrencySymbol          CurrencyDesc  \
2  I was preparing for a job search            THB             Thai baht   
3  I was preparing for a job search            USD  United States dollar   
4  I was preparing for a job search            UAH     Ukrainian hryvnia   

   CompTotal CompFreq  ConvertedComp  WorkWeekHrs  \
2    23000.0  Monthly         8820.0         40.0   
3    61000.0   Yearly        61000.0         80.0   
4        NaN      NaN            NaN         55.0   

                                            WorkPlan  \
2  There's no schedule or spec; I work on what se...   
3  There's no schedule or spec; I work on what se...   
4  There is a schedule and/or spec (made by me or...   

                                       WorkChallenge  \
2  Distracting work environment;Inadequ

Now, let us see how we can access a specific element by using iloc. The default syntax is df.loc[row,"column name"] so we use this to access one element.

Let us look at an example below

In [78]:
df.loc[0,'OpenSourcer'] #Returns the value of opensourcer in first row which is "Never".

'Never'

Now, let us look at the way in which we can access the dataframe by specifying multiple rows and multiple columns. 

The way is simple as all we need to do is to pass the multiple rows and column names as a list and pass them inside the loc function.


Let us look at the example below

In [79]:
df.loc[[0,1],['Country','Student']]

#returns the values of country and student in 1st and 2nd rows

Country         Student
0          United Kingdom              No
1  Bosnia and Herzegovina  Yes, full-time

In [85]:
df.loc[0:2,'Country':'OrgSize']

#returns the values of all columns from country to orgsize in 1st to 3rd rows

Country         Student  \
0          United Kingdom              No   
1  Bosnia and Herzegovina  Yes, full-time   
2                Thailand              No   

                                             EdLevel  \
0                          Primary/elementary school   
1  Secondary school (e.g. American high school, G...   
2           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                  UndergradMajor  \
0                            NaN   
1                            NaN   
2  Web development or web design   

                                            EduOther               OrgSize  
0  Taught yourself a new language, framework, or ...                   NaN  
1  Taken an online course in programming or softw...                   NaN  
2  Taught yourself a new language, framework, or ...  100 to 499 employees

So, these are the ways in which we use both "loc" and "iloc" functions.

loc function is also used in indexing but we will look at it in later part of this notebook

In [81]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ... 
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In order to know the number of values in a column of the dataframe as above, like knowing the number of Yes and No, we can use the value_counts() function as shown below

In [82]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

This returns the number of times each unique value occured in that particular column of the dataframe

# Indexes - How to Set, Reset, and Use Indexes

Index is the default and one of the most prominent column in any dataset. By default, most of the datasets have indexes have ranges from 0 to number of rows-1

However, in Pandas, we have many options wherein we can set our own custom indexes, reset them if we dont want and also create new indexes if we wish for it.


For setting a particular column as an index, all we need to do is to pass in the column name as the parameter inside the set_index() function as shown below

In [89]:
df.set_index('Respondent')

MainBranch Hobbyist  \
Respondent                                                               
1                      I am a student who is learning to code      Yes   
2                      I am a student who is learning to code       No   
3           I am not primarily a developer, but I write co...      Yes   
4                              I am a developer by profession       No   
5                              I am a developer by profession      Yes   
...                                                       ...      ...   
88377                                                     NaN      Yes   
88601                                                     NaN       No   
88802                                                     NaN       No   
88816                                                     NaN       No   
88863                                                     NaN      Yes   

                                                  OpenSourcer  \
Respondent                                                      
1                                                       Never   
2                                     Less than once per year   
3                                                       Never   
4                                                       Never   
5                                  Once a month or more often   
...                                                       ...   
88377       Less than once a month but more than once per ...   
88601                                                   Never   
88802                                                   Never   
88816                                                   Never   
88863                                 Less than once per year   

                                                   OpenSource  \
Respondent                                                      
1           The quality of OSS and closed source software ...   
2           The quality of OSS and closed source software ...   
3           The quality of OSS and closed source software ...   
4           The quality of OSS and closed source software ...   
5           OSS is, on average, of HIGHER quality than pro...   
...                                                       ...   
88377       The quality of OSS and closed source software ...   
88601       The quality of OSS and closed source software ...   
88802                                                     NaN   
88816       OSS is, on average, of HIGHER quality than pro...   
88863       OSS is, on average, of HIGHER quality than pro...   

                                                   Employment  \
Respondent                                                      
1                      Not employed, and not looking for work   
2                          Not employed, but looking for work   
3                                          Employed full-time   
4                                          Employed full-time   
5                                          Employed full-time   
...                                                       ...   
88377                  Not employed, and not looking for work   
88601                                                     NaN   
88802                                      Employed full-time   
88816       Independent contractor, freelancer, or self-em...   
88863                  Not employed, and not looking for work   

                           Country         Student  \
Respondent                                           
1                   United Kingdom              No   
2           Bosnia and Herzegovina  Yes, full-time   
3                         Thailand              No   
4                    United States              No   
5                          Ukraine              No   
...                            ...             ...   
88377                       Canada              No   
88601                          NaN             NaN   
88802     

In [90]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            EduOther  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    OrgSize  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             DevType YearsCode Age1stCode  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       YearsCodePro           CareerSat                 JobSat  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               MgrIdiot  MgrMoney   MgrWant  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             JobSeek          LastHireDate  \
0                                                NaN                   NaN

So, now we can see that the index is set as "Respondent" column in the dataframe as it is unique as well. But when we look at the dataframe in the above cell, we can see that these changes we made are not included in the original dataframe.

For the changes to be reflected in the dataframe, we need to pass in the parameter called "inplace" and set it to True

So, the updated syntax would be like:

df.set_index('colname',inplace=True)

In [99]:
df.set_index('Respondent',inplace=True)

In [100]:
df

MainBranch Hobbyist  \
Respondent                                                               
1                      I am a student who is learning to code      Yes   
2                      I am a student who is learning to code       No   
3           I am not primarily a developer, but I write co...      Yes   
4                              I am a developer by profession       No   
5                              I am a developer by profession      Yes   
...                                                       ...      ...   
88377                                                     NaN      Yes   
88601                                                     NaN       No   
88802                                                     NaN       No   
88816                                                     NaN       No   
88863                                                     NaN      Yes   

                                                  OpenSourcer  \
Respondent                                                      
1                                                       Never   
2                                     Less than once per year   
3                                                       Never   
4                                                       Never   
5                                  Once a month or more often   
...                                                       ...   
88377       Less than once a month but more than once per ...   
88601                                                   Never   
88802                                                   Never   
88816                                                   Never   
88863                                 Less than once per year   

                                                   OpenSource  \
Respondent                                                      
1           The quality of OSS and closed source software ...   
2           The quality of OSS and closed source software ...   
3           The quality of OSS and closed source software ...   
4           The quality of OSS and closed source software ...   
5           OSS is, on average, of HIGHER quality than pro...   
...                                                       ...   
88377       The quality of OSS and closed source software ...   
88601       The quality of OSS and closed source software ...   
88802                                                     NaN   
88816       OSS is, on average, of HIGHER quality than pro...   
88863       OSS is, on average, of HIGHER quality than pro...   

                                                   Employment  \
Respondent                                                      
1                      Not employed, and not looking for work   
2                          Not employed, but looking for work   
3                                          Employed full-time   
4                                          Employed full-time   
5                                          Employed full-time   
...                                                       ...   
88377                  Not employed, and not looking for work   
88601                                                     NaN   
88802                                      Employed full-time   
88816       Independent contractor, freelancer, or self-em...   
88863                  Not employed, and not looking for work   

                           Country         Student  \
Respondent                                           
1                   United Kingdom              No   
2           Bosnia and Herzegovina  Yes, full-time   
3                         Thailand              No   
4                    United States              No   
5                          Ukraine              No   
...                            ...             ...   
88377                       Canada              No   
88601                          NaN             NaN   
88802     

Now, we can see that these changes are reflected in the dataframe as well.


Now, sometimes we want to reset our index back to the default index and pandas has a method called "reset_index" which does that.

The syntax would be like: 
df.reset_index(inplace=True)

In [101]:
df.reset_index(inplace=True)

In [103]:
df.head() #Now, we can see that the dataset is back to its original index

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            EduOther  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    OrgSize  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             DevType YearsCode Age1stCode  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       YearsCodePro           CareerSat                 JobSat  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               MgrIdiot  MgrMoney   MgrWant  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             JobSeek          LastHireDate  \
0                                                NaN                   NaN

We can view the index of the dataframe by using the "df.index" attribute as shown below


In [107]:
df.index #Here the index is in the range(0,88883)

RangeIndex(start=0, stop=88883, step=1)

If we know the index which we can use while reading the dataframe, we can use a special paramter called "index_col" inside the read_csv function to specify the index while reading the dataframe.

This saves us both the effort and minimises the code to randomly setup the index later.

The syntax is like:
pd.read_csv('filename.csv",index_col='colname')

In [109]:
pd.read_csv('survey_results_public.csv',index_col='Respondent')

#Now, we can see that the 'Respondent' column is automatically chosen to be the index

MainBranch Hobbyist  \
Respondent                                                               
1                      I am a student who is learning to code      Yes   
2                      I am a student who is learning to code       No   
3           I am not primarily a developer, but I write co...      Yes   
4                              I am a developer by profession       No   
5                              I am a developer by profession      Yes   
...                                                       ...      ...   
88377                                                     NaN      Yes   
88601                                                     NaN       No   
88802                                                     NaN       No   
88816                                                     NaN       No   
88863                                                     NaN      Yes   

                                                  OpenSourcer  \
Respondent                                                      
1                                                       Never   
2                                     Less than once per year   
3                                                       Never   
4                                                       Never   
5                                  Once a month or more often   
...                                                       ...   
88377       Less than once a month but more than once per ...   
88601                                                   Never   
88802                                                   Never   
88816                                                   Never   
88863                                 Less than once per year   

                                                   OpenSource  \
Respondent                                                      
1           The quality of OSS and closed source software ...   
2           The quality of OSS and closed source software ...   
3           The quality of OSS and closed source software ...   
4           The quality of OSS and closed source software ...   
5           OSS is, on average, of HIGHER quality than pro...   
...                                                       ...   
88377       The quality of OSS and closed source software ...   
88601       The quality of OSS and closed source software ...   
88802                                                     NaN   
88816       OSS is, on average, of HIGHER quality than pro...   
88863       OSS is, on average, of HIGHER quality than pro...   

                                                   Employment  \
Respondent                                                      
1                      Not employed, and not looking for work   
2                          Not employed, but looking for work   
3                                          Employed full-time   
4                                          Employed full-time   
5                                          Employed full-time   
...                                                       ...   
88377                  Not employed, and not looking for work   
88601                                                     NaN   
88802                                      Employed full-time   
88816       Independent contractor, freelancer, or self-em...   
88863                  Not employed, and not looking for work   

                           Country         Student  \
Respondent                                           
1                   United Kingdom              No   
2           Bosnia and Herzegovina  Yes, full-time   
3                         Thailand              No   
4                    United States              No   
5                          Ukraine              No   
...                            ...             ...   
88377                       Canada              No   
88601                          NaN             NaN   
88802     

Now, I made the index of the schema dataframe to be column as we can easily search the meaning of the column name just by using the loc function as shown below. Note that, we cannot use the iloc function anymore for this as index is not an integer

In [121]:
schema_df.head() #Column is the index

QuestionText
Column                                                        
Respondent   Randomized respondent ID number (not in order ...
MainBranch   Which of the following options best describes ...
Hobbyist                               Do you code as a hobby?
OpenSourcer        How often do you contribute to open source?
OpenSource   How do you feel about the quality of open sour...

In [124]:
schema_df.loc['Hobbyist'] #Finding the meaning of "Hobbyist" column by using loc

QuestionText    Do you code as a hobby?
Name: Hobbyist, dtype: object

Although, we made the index to the column names, it looks good if they are to be arranged in an alphabetical order.

We can do this by using the "sort_index"() function as shown below

In [128]:
schema_df.sort_index(inplace=True)

In [129]:
schema_df.head()

QuestionText
Column                                                          
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...

In [130]:
schema_df.sort_index(inplace=True,ascending=False) #To sort indescending order

In [133]:
schema_df.head()

QuestionText
Column                                                         
YearsCodePro  How many years have you coded professionally (...
YearsCode     Including any education, how many years have y...
WorkWeekHrs    On average, how many hours per week do you work?
WorkRemote                      How often do you work remotely?
WorkPlan                How structured or planned is your work?

# Filtering - Using Conditionals to Filter Rows and Columns

Filtering is one of the most essential operations which we perform on a dataset based on various conditions and to extract some insights. 

Now, let us look at some ways in which we perform filtering.

We can filter data by specifying a filter condition and then passing the condition inside a dataframe to obtain the filtered dataframe.

For doing this, we can either use .loc function or the normal calling function.

Now, let us take an example of the Public dataset. We want to find out the 'Employment' and "Main Branch" of all the people who reside in the "United States".

First let us do this by the normal method.

The normal method is to create a filter function for "United States" and pass this inside a DataFrame by using the syntax like:- df[filtercondition] and then accessing these two specific columns of the new dataframe by using the loc function. We wont be using the iloc function as it is difficult to count the column number of specific columns all the time

In [138]:
#Specifying the filter function. This returns a series of True and False based on the condition
filt = df['Country']=='United States'

filt

0        False
1        False
2        False
3         True
4        False
         ...  
88878    False
88879    False
88880    False
88881    False
88882    False
Name: Country, Length: 88883, dtype: bool

In [142]:
#Passing the filter function inside dataframe to obtain a filtered dataframe

df[filt].head()

Respondent                      MainBranch Hobbyist  \
3            4  I am a developer by profession       No   
12          13  I am a developer by profession      Yes   
21          22  I am a developer by profession      Yes   
22          23  I am a developer by profession      Yes   
25          26  I am a developer by profession      Yes   

                                          OpenSourcer  \
3                                               Never   
12  Less than once a month but more than once per ...   
21                            Less than once per year   
22                            Less than once per year   
25                            Less than once per year   

                                           OpenSource          Employment  \
3   The quality of OSS and closed source software ...  Employed full-time   
12  OSS is, on average, of HIGHER quality than pro...  Employed full-time   
21  OSS is, on average, of HIGHER quality than pro...  Employed full-time   
22  The quality of OSS and closed source software ...  Employed full-time   
25  The quality of OSS and closed source software ...  Employed full-time   

          Country Student                                            EdLevel  \
3   United States      No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
12  United States      No        Master’s degree (MA, MS, M.Eng., MBA, etc.)   
21  United States      No  Some college/university study without earning ...   
22  United States      No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
25  United States      No  Some college/university study without earning ...   

                                       UndergradMajor  \
3   Computer science, computer engineering, or sof...   
12  Computer science, computer engineering, or sof...   
21                                                NaN   
22  Information systems, information technology, o...   
25  Computer science, computer engineering, or sof...   

                                             EduOther  \
3   Taken an online course in programming or softw...   
12  Taken an online course in programming or softw...   
21  Taken an online course in programming or softw...   
22  Taken an online course in programming or softw...   
25  Taught yourself a new language, framework, or ...   

                     OrgSize  \
3       100 to 499 employees   
12        10 to 19 employees   
21  10,000 or more employees   
22  10,000 or more employees   
25  10,000 or more employees   

                                              DevType YearsCode Age1stCode  \
3                               Developer, full-stack         3         16   
12  Data or business analyst;Database administrato...        17         11   
21  Data or business analyst;Designer;Developer, b...        35         12   
22                              Developer, full-stack         3         19   
25  Designer;Developer, back-end;Developer, deskto...        12          8   

        YearsCodePro           CareerSat              JobSat  \
3   Less than 1 year      Very satisfied  Slightly satisfied   
12                 8      Very satisfied      Very satisfied   
21                18  Slightly satisfied   Very dissatisfied   
22                 1  Slightly satisfied  Slightly satisfied   
25                 8      Very satisfied      Very satisfied   

              MgrIdiot MgrMoney   MgrWant  \
3       Very confident       No  Not sure   
12                 NaN      NaN       NaN   
21  Somewhat confident       No        No   
22      Very confident       No  Not sure   
25                 NaN      NaN       NaN   

                                              JobSeek           LastHireDate  \
3        I am not interested in new job opportunities   Less than a year ago   
12       I am not interested in new job opportunities          3-4 years ago   
21  I’m not actively looking, but I am open to new...  More than 4 years ago   
22  I’m not actively looking, but I am

In [143]:
#Finally accessing the specific columns to get the desired output

df[filt].loc[:,['Employment','MainBranch']].head()

Employment                      MainBranch
3   Employed full-time  I am a developer by profession
12  Employed full-time  I am a developer by profession
21  Employed full-time  I am a developer by profession
22  Employed full-time  I am a developer by profession
25  Employed full-time  I am a developer by profession

The other way is to do by using the .loc function. Although this is similar to the previous method in steps, we can reduce the complexity of code vastly by using the .loc function.

We know that the .loc() takes two parameters as an input which are [rows,column names]. Now, we can obtain the needed data by passing the filtered condtion as rows and the required column names as a list of columns inside loc to get the final dataframe

In [145]:
df.loc[filt,['Employment','MainBranch']].head()

Employment                      MainBranch
3   Employed full-time  I am a developer by profession
12  Employed full-time  I am a developer by profession
21  Employed full-time  I am a developer by profession
22  Employed full-time  I am a developer by profession
25  Employed full-time  I am a developer by profession

We can even use the 'And' and 'Or' operators to filter various conditions based on our requirement.

A key point to note is that, in Pandas we have to use the symbols & and | for 'And' and 'Or' operations.

Let us look at an example

In [148]:
#Finding the people who reside in United States and not a student. We use paranthesis to seperate multiple conditions.

filt = ((df['Country']=='United States') & (df['Student']=='No'))
filt

0        False
1        False
2        False
3         True
4        False
         ...  
88878    False
88879    False
88880    False
88881    False
88882    False
Length: 88883, dtype: bool

In [153]:
#Finding the employment status of these filtered people

df.loc[filt].head()

Respondent                      MainBranch Hobbyist  \
3            4  I am a developer by profession       No   
12          13  I am a developer by profession      Yes   
21          22  I am a developer by profession      Yes   
22          23  I am a developer by profession      Yes   
25          26  I am a developer by profession      Yes   

                                          OpenSourcer  \
3                                               Never   
12  Less than once a month but more than once per ...   
21                            Less than once per year   
22                            Less than once per year   
25                            Less than once per year   

                                           OpenSource          Employment  \
3   The quality of OSS and closed source software ...  Employed full-time   
12  OSS is, on average, of HIGHER quality than pro...  Employed full-time   
21  OSS is, on average, of HIGHER quality than pro...  Employed full-time   
22  The quality of OSS and closed source software ...  Employed full-time   
25  The quality of OSS and closed source software ...  Employed full-time   

          Country Student                                            EdLevel  \
3   United States      No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
12  United States      No        Master’s degree (MA, MS, M.Eng., MBA, etc.)   
21  United States      No  Some college/university study without earning ...   
22  United States      No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
25  United States      No  Some college/university study without earning ...   

                                       UndergradMajor  \
3   Computer science, computer engineering, or sof...   
12  Computer science, computer engineering, or sof...   
21                                                NaN   
22  Information systems, information technology, o...   
25  Computer science, computer engineering, or sof...   

                                             EduOther  \
3   Taken an online course in programming or softw...   
12  Taken an online course in programming or softw...   
21  Taken an online course in programming or softw...   
22  Taken an online course in programming or softw...   
25  Taught yourself a new language, framework, or ...   

                     OrgSize  \
3       100 to 499 employees   
12        10 to 19 employees   
21  10,000 or more employees   
22  10,000 or more employees   
25  10,000 or more employees   

                                              DevType YearsCode Age1stCode  \
3                               Developer, full-stack         3         16   
12  Data or business analyst;Database administrato...        17         11   
21  Data or business analyst;Designer;Developer, b...        35         12   
22                              Developer, full-stack         3         19   
25  Designer;Developer, back-end;Developer, deskto...        12          8   

        YearsCodePro           CareerSat              JobSat  \
3   Less than 1 year      Very satisfied  Slightly satisfied   
12                 8      Very satisfied      Very satisfied   
21                18  Slightly satisfied   Very dissatisfied   
22                 1  Slightly satisfied  Slightly satisfied   
25                 8      Very satisfied      Very satisfied   

              MgrIdiot MgrMoney   MgrWant  \
3       Very confident       No  Not sure   
12                 NaN      NaN       NaN   
21  Somewhat confident       No        No   
22      Very confident       No  Not sure   
25                 NaN      NaN       NaN   

                                              JobSeek           LastHireDate  \
3        I am not interested in new job opportunities   Less than a year ago   
12       I am not interested in new job opportunities          3-4 years ago   
21  I’m not actively looking, but I am open to new...  More than 4 years ago   
22  I’m not actively looking, but I am

In [154]:
#An example for Or
#Finding the people who reside in United States and not a student. We use paranthesis to seperate multiple conditions.

filt = ((df['Country']=='United States') | (df['Student']=='No'))
df[filt].head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   
5           6  I am not primarily a developer, but I write co...      Yes   

                  OpenSourcer  \
0                       Never   
2                       Never   
3                       Never   
4  Once a month or more often   
5                       Never   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   
5  The quality of OSS and closed source software ...   

                               Employment         Country Student  \
0  Not employed, and not looking for work  United Kingdom      No   
2                      Employed full-time        Thailand      No   
3                      Employed full-time   United States      No   
4                      Employed full-time         Ukraine      No   
5                      Employed full-time          Canada      No   

                                    EdLevel  \
0                 Primary/elementary school   
2  Bachelor’s degree (BA, BS, B.Eng., etc.)   
3  Bachelor’s degree (BA, BS, B.Eng., etc.)   
4  Bachelor’s degree (BA, BS, B.Eng., etc.)   
5  Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  \
0                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   
5                          Mathematics or statistics   

                                            EduOther  \
0  Taught yourself a new language, framework, or ...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   
5  Taken an online course in programming or softw...   

                    OrgSize  \
0                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   
5                       NaN   

                                             DevType YearsCode Age1stCode  \
0                                                NaN         4         10   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   
5  Data or business analyst;Data scientist or mac...        13         15   

       YearsCodePro           CareerSat                 JobSat  \
0               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   
5                 3      Very satisfied     Slightly satisfied   

               MgrIdiot  MgrMoney   MgrWant  \
0                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   
5        Very confident        No       Yes   

                                             JobSeek          LastHireDate  \
0                                                NaN                   NaN   
2  I’m not actively looking, but I am open to new...         1-2 years ago   
3       I am not interested in new job opportunities  Less than a ye

We can even use the not operator in a similar way

Now, let us look at some filters by using some examples

In [160]:
high_sal = df['ConvertedComp']>70000
df.loc[high_sal,['Country','LanguageWorkedWith','ConvertedComp']]

Country                                 LanguageWorkedWith  \
5              Canada                                         Java;R;SQL   
8         New Zealand  Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...   
12      United States  Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...   
15     United Kingdom  Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...   
21      United States  Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...   
...               ...                                                ...   
88323   United States  Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...   
88324   United States  Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...   
88325   United States               HTML/CSS;JavaScript;Scala;TypeScript   
88326         Finland                   Bash/Shell/PowerShell;C++;Python   
88329     Netherlands             C#;HTML/CSS;Java;JavaScript;PHP;Python   

       ConvertedComp  
5           366420.0  
8            95179.0  
12           90000.0  
15          455352.0  
21          103000.0  
...              ...  
88323       180000.0  
88324      2000000.0  
88325       130000.0  
88326        82488.0  
88329       588012.0  

[22289 rows x 3 columns]

In [164]:
#We can usethe isin() operator to find the list of column values in column

countries = ['United States','India','United Kingdom','Canada','Germany']
filt = df['Country'].isin(countries)

In [165]:
df.loc[filt,'Country']

0        United Kingdom
3         United States
5                Canada
7                 India
9                 India
              ...      
88859     United States
88863    United Kingdom
88864             India
88877     United States
88878            Canada
Name: Country, Length: 45008, dtype: object

Sometimes, the value of a certain column isn't necessarily a string or a value instead it can be a list of strings or values or dictionaries etc.

In these cases, we cannot directly use the isin() function or the == to filter them.String functions come in hand y in these cases.

Now, let us look at the most commonly used the string method called str.contains().

This takes in the string as an input argument which it searches and also a default na value incase the column has any null values in it.


Now,let us look at an example wherein we filter the people based on if they worked with Python language and seperate the ones.

In [169]:
df['LanguageWorkedWith'].head()

0                HTML/CSS;Java;JavaScript;Python
1                            C++;HTML/CSS;Python
2                                       HTML/CSS
3                            C;C++;C#;Python;SQL
4    C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
Name: LanguageWorkedWith, dtype: object

In [170]:
filt = df['LanguageWorkedWith'].str.contains('Python', na=False)
df.loc[filt,'LanguageWorkedWith'].head()

0                      HTML/CSS;Java;JavaScript;Python
1                                  C++;HTML/CSS;Python
3                                  C;C++;C#;Python;SQL
4          C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
7    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
Name: LanguageWorkedWith, dtype: object

# Updating Rows and Columns - Modifying Data Within DataFrames

Now that we have seen how to filter the rows based on some conditions, let us now look at how we can use these filtering conditions to update and modify various rows within the dataframes

In [185]:
#looking at all the columns
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

There are a couple of ways in which we can change the name of the columns which we will look over now.

1. Manually assigning all the columns to a list of new column names
2. Using the .rename() function

The first method is to pass in all the new column names inside a list and assigning it to the df.columns to update it

In [214]:
#Let us take a small dataframe to do it quickly for this

people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

dfa = pd.DataFrame(people)

dfa

first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [216]:
#Passing the new names as a list to the default df.columns

dfa.columns = ['FirstName','LastName','Email']


In [218]:
#We can see the new column names inside the dataframe
dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John      Doe        JohnDoe@email.com

This method isnt useful as this only works for the case in which we want to replace the names of all the columns and not just some columns

In [220]:
#We can change the case of all the column names by using df.columns

df.columns = [i.upper() for i in df.columns]

df.head()

RESPONDENT                                         MAINBRANCH HOBBYIST  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OPENSOURCER  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OPENSOURCE  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               EMPLOYMENT                 COUNTRY  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          STUDENT                                            EDLEVEL  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UNDERGRADMAJOR  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            EDUOTHER  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    ORGSIZE  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             DEVTYPE YEARSCODE AGE1STCODE  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       YEARSCODEPRO           CAREERSAT                 JOBSAT  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               MGRIDIOT  MGRMONEY   MGRWANT  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             JOBSEEK          LASTHIREDATE  \
0                                                NaN                   NaN

In [221]:
#We can change the case of all the column names by using df.columns

df.columns = [i.lower() for i in df.columns]

df.head()

respondent                                         mainbranch hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  opensourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          opensource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               employment                 country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          student                                            edlevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      undergradmajor  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            eduother  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    orgsize  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             devtype yearscode age1stcode  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       yearscodepro           careersat                 jobsat  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               mgridiot  mgrmoney   mgrwant  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             jobseek          lasthiredate  \
0                                                NaN                   NaN

The second method to rename is by using the .rename() function. This function is widely used as this replaces the names of the specific columns with a new value.

The syntax is:- df.rename(columns = {col1name:newcol1name, col2name:newcol2name......},inplace=True)

In [227]:
#Let us rename the respondent and mainbranch to 'UniqueID' and 'Branch'

df.rename(columns = {'respondent':'UniqueID','mainbranch':'Branch'},inplace=True)


In [228]:
df.head()

UniqueID                                             Branch hobbyist  \
0         1             I am a student who is learning to code      Yes   
1         2             I am a student who is learning to code       No   
2         3  I am not primarily a developer, but I write co...      Yes   
3         4                     I am a developer by profession       No   
4         5                     I am a developer by profession      Yes   

                  opensourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          opensource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               employment                 country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          student                                            edlevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      undergradmajor  \
0                                                NaN   
1                                                NaN   
2                      Web development or web design   
3  Computer science, computer engineering, or sof...   
4  Computer science, computer engineering, or sof...   

                                            eduother  \
0  Taught yourself a new language, framework, or ...   
1  Taken an online course in programming or softw...   
2  Taught yourself a new language, framework, or ...   
3  Taken an online course in programming or softw...   
4  Taken an online course in programming or softw...   

                    orgsize  \
0                       NaN   
1                       NaN   
2      100 to 499 employees   
3      100 to 499 employees   
4  10,000 or more employees   

                                             devtype yearscode age1stcode  \
0                                                NaN         4         10   
1  Developer, desktop or enterprise applications;...       NaN         17   
2  Designer;Developer, back-end;Developer, front-...         3         22   
3                              Developer, full-stack         3         16   
4  Academic researcher;Developer, desktop or ente...        16         14   

       yearscodepro           careersat                 jobsat  \
0               NaN                 NaN                    NaN   
1               NaN                 NaN                    NaN   
2                 1  Slightly satisfied     Slightly satisfied   
3  Less than 1 year      Very satisfied     Slightly satisfied   
4                 9   Very dissatisfied  Slightly dissatisfied   

               mgridiot  mgrmoney   mgrwant  \
0                   NaN       NaN       NaN   
1                   NaN       NaN       NaN   
2  Not at all confident  Not sure  Not sure   
3        Very confident        No  Not sure   
4    Somewhat confident       Yes        No   

                                             jobseek          lasthiredate  \
0                                                NaN                   NaN   
1       

Now, let us look at how we can update the values in our rows by using loc and iloc by using the sample dataframe dfa

In [229]:
dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John      Doe        JohnDoe@email.com

In [231]:
#Grabbing the data at index location 2
dfa.loc[2]

FirstName                 John
LastName                   Doe
Email        JohnDoe@email.com
Name: 2, dtype: object

In [232]:
#Changing last name to smith and email as well
dfa.loc[2] = ['John','Smith','JohnSmith@gmail.com']

dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John    Smith      JohnSmith@gmail.com

This is inefficient as for more entries datasets, we can use loc to grab some specific values of the dataframes

In [235]:
#Grabbing only specific values of specific columns

dfa.loc[2,['LastName','Email']] = ['Doe','JohnDoe@email.com']
dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John      Doe        JohnDoe@email.com

In [240]:
#Changing only one value by using loc
dfa.loc[2,'LastName'] = 'Smith'

dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John    Smith        JohnDoe@email.com

Pandas has a specific function called 'at' which performs the same function as .loc as we used above. Let us look at an example


In [242]:
#Changing lastname of John to Doe again

dfa.at[2,'LastName'] = 'Doe'

dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John      Doe        JohnDoe@email.com

One of the common mistakes which we can do is as follows. Let us look at an example below.

Here, we tried accessing the last name of "John" by using a filter condition and then accessing the lastname of that dataframe.

Then we tried to set that value to "Smith" which resulted in an error.

This is due to the fact that the dataframe we created is a subset and a temporary dataframe and can be tossed out anytime.

So, make sure to change the values only by using the .loc method

In [249]:
filt = (dfa['Email'] == 'JohnDoe@email.com')
dfa[filt]['LastName']

2    Doe
Name: LastName, dtype: object

In [250]:
dfa[filt]['LastName'] = 'Smith'

C:\Users\Rahul M\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [252]:
#We can see that the LastName isnt changed
dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John      Doe        JohnDoe@email.com

In [253]:
#Correcting that mistake

dfa.loc[filt,'LastName'] = 'Smith'
dfa

FirstName LastName                    Email
0     Corey  Schafer  CoreyMSchafer@gmail.com
1      Jane      Doe        JaneDoe@email.com
2      John    Smith        JohnDoe@email.com

In [262]:
#Let us now change all the emails to lowercase

dfa['Email'] = dfa['Email'].str.lower()

dfa

FirstName LastName                    Email
0     Corey  Schafer  coreymschafer@gmail.com
1      Jane      Doe        janedoe@email.com
2      John    Smith        johndoe@email.com

Now, let us do some advanced operations on changing the values in columns. There are 4 different methods in which we can change all the values of a certain column based on some conditions.

1. apply()
2. map()
3. applymap()
4. replace()

Let us look at each of them in detail.

Apply is used to call a function onto a value. This can be used for both Series and Dataframes. Let us look at how it works on a Series and Dataframe.

In [265]:
#We used the apply function to find length of email addresses of a series

dfa['Email'].apply(len)

0    23
1    17
2    17
Name: Email, dtype: int64

Now, let us look at how we can update values based on a function.

For example, we ar gonna create a function that changes the email address to uppercase in all entries.

In [266]:
def update(email):
    return email.upper()


In [268]:
#Applying this function to email column

dfa['Email'] = dfa['Email'].apply(update)

dfa

FirstName LastName                    Email
0     Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1      Jane      Doe        JANEDOE@EMAIL.COM
2      John    Smith        JOHNDOE@EMAIL.COM

We can use the same steps for updating the values based on a complex function as well

In [272]:
#Converting the emails back to lowercase by using "lambda" function

dfa['Email'] = dfa['Email'].apply(lambda x: x.lower())

dfa

#We can either use lambda or a custom function based on ur comfort

FirstName LastName                    Email
0     Corey  Schafer  coreymschafer@gmail.com
1      Jane      Doe        janedoe@email.com
2      John    Smith        johndoe@email.com

Now, let us see how the apply function works on a dataframe.

When we run apply on an entire dataframe, it runs on each row and column of a dataframe.

In [274]:
dfa.apply(len)

FirstName    3
LastName     3
Email        3
dtype: int64

This result might come to be unexpected as we expected the function to give out the length of each value but in this case, the len function is returning the number of entries in each column of this dataframe.

So, FirstName has 3 rows called Corey,John,Jane. Thats why it returned 3

In [277]:
#This is the function thats happening

len(dfa['FirstName'])

3

In [279]:
#Lets find the minimum value of each column in this dataframe
dfa.apply(pd.Series.min)

FirstName                      Corey
LastName                         Doe
Email        coreymschafer@gmail.com
dtype: object

So, to sum the apply() function,
1. It applies the function to each value of the series.
2. It applies the function to each row and column in the dataframe and not their values

Sometimes, we need the function to be applied to each and every value in the dataframe and this is precisely when we use the applymap() function.

Applymap() function only works on dataframes and not series and it applies a certain condition to all the values in a dataframe

In [283]:
#We can see that it runs the len function on each value of the dataframe and returns their length

dfa.applymap(len)

FirstName  LastName  Email
0          5         7     23
1          4         3     17
2          4         5     17

In [299]:
def func(s):
    return s.lower()
dfa = dfa.applymap(func)

In [302]:
dfa

FirstName LastName                    Email
0     corey  schafer  coreymschafer@gmail.com
1      jane      doe        janedoe@email.com
2      john    smith        johndoe@email.com

Now. let us look at the map() function.

map() funcion only works on a series. This is mainly used to subsitute various values in a series inplace of already exisitng values.

map() takes in a dictionary of values as {exisiting value:new value} and replaces them at all occurances

In [304]:
dfa['FirstName'].map({'corey':'Rahul','jane':'emma'})


0    Rahul
1     emma
2      NaN
Name: FirstName, dtype: object

Here, we notice a problem that whatever values which we havent specified as a dictionary are replaced as nan values when map() is used.

So we only use map functions wherein the unique values in that column are minimum like Yes/No or 0/1 etc

Whatif we wanted to update only the selected values and keep other values as it is?

This is when we use replace() function.

replace() function replaces only the specified values and leaves the others as it is

In [306]:
#Here, we can see that the name john is retained as we wanted to be

dfa['FirstName'].replace({'corey':'Rahul','jane':'emma'})


0    Rahul
1     emma
2     john
Name: FirstName, dtype: object

Now, let us use this knowledge to work on our larger dataset which is the "Public" dataset we already have

In [341]:
#Let us rename the "ConvertedComp" column to "SalaryUSD" and keep it permanent
df.rename(columns={'ConvertedComp': 'SalaryUSD'}, inplace=True)

In [342]:
#We can see that the change is reflected into the original dataframe

df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...   
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [343]:
#Lets look at this column now. We can clearly see that the only values in this are Yes and No.


df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ... 
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [344]:
#So, lets change the values of Yes and No to True or False by using the map() function

df['Hobbyist'] = df['Hobbyist'].map({'Yes':'True','No':'False'})
df['Hobbyist']

#We can see the changes clearly

0         True
1        False
2         True
3        False
4         True
         ...  
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: object